services:
#  spring-app:
#    build:
#      context: .
#      dockerfile: Dockerfile
#    container_name: create-spring-app-dev
#    ports:
#      - "8080:8080"
#    env_file:
#      - create-spring-app.env
#    depends_on:
#      redis:
#        condition: service_healthy
#      mysql:
#        condition: service_healthy
#    environment:
#      - TZ=Asia/Seoul

  redis:
    image: 'redis:latest'
    container_name: create-spring-app-redis-dev
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  mysql:
    image: mysql:8.4
    container_name: create-spring-app-mysql-dev
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 10
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=create-spring-app
      - MYSQL_USER=${DB_USERNAME}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - TZ=Asia/Seoul
    ports:
      - "3307:3306"
    volumes:
      - mysql_data_dev:/var/lib/mysql
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci

volumes:
  mysql_data_dev:
